#!/bin/sh

# Shell script to wrap 'wtime' and report hours worked
if [ -z "$1" ]; then
  echo "Usage: $0 <task name>"
	exit 1;
  else
	if [ ! -d ~/.wtimed ] || [ ! -s ~/.wtimed/$1 ]; then
		echo "Either ~/.wtimed does not exist or the task '$1' does not exist."
		exit 1
	else
		out=`python -c "print  $(wtime -t $1 -r '01-01-1970')/60.0/60.0"`
	  echo -n "Hours worked: $out"	
	fi
fi
